name: 'trunk-action'
description:
  'Install Trunk by downloading the executable (much faster than cargo install
  trunk, seconds vs minutes).'
author: 'jetli'
inputs:
  version:
    description:
      'Optional version of trunk to install (eg. "v0.21.14", "latest")'
    default: 'latest'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'package'
  color: 'orange'
